# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0773bb512dee537587dcfaa1426bc0a85d94347e0f6176ea3f359eae9d51e37636e414e6f0addb7d7a5c861ce32eb1ef1ad37d22f76efd3cde4afbb87ffb6af

test:
  secret_key_base: bc6f18670e46826800de82e0012e779592b15d0c59424f6a3685fed9a2122151c73a49fc1201d1027c39f2363682464fb0cadb8624b514424e2d216f79f1ac48

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
